package scalf.project1.util;

enum Keyword {
	WINDOW, END,
	LAYOUT, FLOW, GRID,
	BUTTON, GROUP, LABEL, PANEL, TEXTFIELD,
	RADIO,
	OPEN_PARENTHESIS, COMMA, CLOSE_PARENTHESIS,
	PERIOD, COLON, SEMICOLON,
	STRING, NUMBER
}
